=== A-vives/FP-/Lenguaje_de_Marcas/XML/ACT.5.1/5/data.dtd
<!ELEMENT NACEX (camioneros, provincias, camiones)>
<!ELEMENT camioneros (camionero+, paquetes?)>
    <!ELEMENT camionero (paquetes+)>
        <!ATTLIST camionero id ID #REQUIRED>
        <!ATTLIST camionero nombre CDATA #REQUIRED>
        <!ATTLIST camionero cam_tlf CDATA #REQUIRED>
        <!ATTLIST camionero cam_dir CDATA #REQUIRED>
        <!ATTLIST camionero cam_sal CDATA #REQUIRED>
        <!ATTLIST camionero ciudad CDATA #REQUIRED>
    <!ELEMENT paquetes (paquete+)>
    <!ELEMENT paquete (destinatario)>
        <!ATTLIST paquete id ID #REQUIRED>
        <!ATTLIST paquete codigo_provincia CDATA #REQUIRED>
        <!ATTLIST paquete descripcion CDATA #REQUIRED>
<!ELEMENT destinatario (#PCDATA)>
    <!ATTLIST destinatario nombre CDATA #REQUIRED>
    <!ATTLIST destinatario direccion_envio CDATA #REQUIRED>

<!ELEMENT provincias (provincia+)>

    <!ELEMENT provincia (#PCDATA)>
        <!ATTLIST provincia codigo CDATA #REQUIRED>
        <!ATTLIST provincia nombre CDATA #REQUIRED>

<!ELEMENT camiones (camion+)>
<!ELEMENT camion (conductores*)>
    <!ATTLIST camion id ID #REQUIRED>
    <!ATTLIST camion matricula CDATA #REQUIRED>
    <!ATTLIST camion modelo CDATA #REQUIRED>
    <!ATTLIST camion tipo CDATA #REQUIRED>
    <!ATTLIST camion potencia CDATA #REQUIRED>
<!ELEMENT conductores (conductor+)>
<!ELEMENT conductor (#PCDATA)>
    <!ATTLIST conductor id IDREF #REQUIRED>

=== A-vives/FP-/Lenguaje_de_Marcas/XML/ACT.5.1/5/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NACEX SYSTEM "data.dtd">
<NACEX>
    <camioneros>
      <camionero id="C01" nombre="" cam_tlf="" cam_dir="" cam_sal="" ciudad="">

        <paquetes>
          <paquete id="P01" codigo_provincia="" descripcion="">
            <destinatario nombre="" direccion_envio=""></destinatario>
          </paquete>

          <paquete id="P02" codigo_provincia="" descripcion="">
            <destinatario nombre="" direccion_envio=""></destinatario>
          </paquete>

        </paquetes>

      </camionero>
      <camionero id="C02" nombre="" cam_tlf="" cam_dir="" cam_sal="" ciudad="">

        <paquetes>
          <paquete id="P03" codigo_provincia="" descripcion="">
            <destinatario nombre="" direccion_envio=""></destinatario>
          </paquete>

        </paquetes>
      </camionero>
    </camioneros>

    <provincias>
      <provincia codigo="P001" nombre="Valencia"></provincia>
      <provincia codigo="P002" nombre="Madrid"></provincia>
    </provincias>

    <camiones>
      <camion id="CA001" matricula="1234CVD" modelo="PICK" tipo="" potencia="">
        
        <conductores>

          <conductor id="C01"/>
          <conductor id="C02"/>

        </conductores>
      </camion>

      <camion id="CA002" matricula="1234CDS" modelo="" tipo="" potencia="">

        <conductores>
          <conductor id="C01"/>
        </conductores>

      </camion>
    </camiones>

  </NACEX>
