=== A-vives/FP-/Lenguaje_de_Marcas/XML/DTD1.dtd
<!ELEMENT company (clientes+, supliers+)>
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (purchase+)>
<!ELEMENT purchase EMPTY>
<!ELEMENT supliers (suplier+)>
<!ELEMENT suplier (product*)>
<!ELEMENT product EMPTY>

<!ATTLIST cliente name CDATA #REQUIRED>
<!ATTLIST cliente address CDATA #REQUIRED>
<!ATTLIST cliente surname CDATA #REQUIRED>
<!ATTLIST cliente birthday CDATA #REQUIRED>

<!ATTLIST suplier nif CDATA #REQUIRED>
<!ATTLIST suplier name CDATA #REQUIRED>
<!ATTLIST suplier address CDATA #REQUIRED>

<!ATTLIST product code CDATA #REQUIRED>
<!ATTLIST product name CDATA #REQUIRED>
<!ATTLIST product price CDATA #REQUIRED>

=== A-vives/FP-/Lenguaje_de_Marcas/XML/Documento1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE company SYSTEM "file:/C:/Users/Alejandro/GUITHUB_LOCAL/CLASE/Lenguaje_de_Marcas/XML/DTD1.dtd">
<company>

<clientes>

    <cliente name="antonio" surname="00001" address="xxx" birthday="01-01-2002" >
        <purchase/>
    </cliente>

</clientes>

<supliers >
    <suplier nif="3333" name="001" address="xxx">
        <product code="1" name="silla" price="34"/>
        <product code="2" name="lampara" price="50"/>
    </suplier>
</supliers>

</company>
