=== A-vives/FP-/Lenguaje_de_Marcas/XML/airline/data_airline.dtd
<!ELEMENT airline_DB (airlines, passengers, airports)>
<!ELEMENT airlines (airline+)>
<!ELEMENT airline (airplanes*)>
<!ATTLIST airline name CDATA #REQUIRED>

<!ELEMENT airplanes (airplane+)>

<!ELEMENT airplane (flight*)>
<!ATTLIST airplane reg_num CDATA #REQUIRED>
<!ATTLIST airplane model CDATA #REQUIRED>
<!ATTLIST airplane capacity CDATA #REQUIRED>

<!ELEMENT flight EMPTY>
<!ATTLIST flight fl_num CDATA #REQUIRED>
<!ATTLIST flight dep_airport CDATA #REQUIRED>
<!ATTLIST flight dest_airport CDATA #REQUIRED>
<!ATTLIST flight dep_date CDATA #REQUIRED>
<!ATTLIST flight dest_date CDATA #REQUIRED>

<!ELEMENT passengers (passenger+)>
<!ELEMENT passenger (booking*)>
<!ATTLIST passenger name CDATA #REQUIRED>
<!ATTLIST passenger surname CDATA #REQUIRED>
<!ATTLIST passenger email CDATA #REQUIRED>
<!ATTLIST passenger seat NMTOKEN #REQUIRED>

<!ELEMENT booking EMPTY>
<!ATTLIST booking idflight CDATA #REQUIRED>
<!ATTLIST booking seat NMTOKEN #REQUIRED>
<!ELEMENT airports (airport*)>
<!ELEMENT airport EMPTY>
<!ATTLIST airport name CDATA #REQUIRED>

=== A-vives/FP-/Lenguaje_de_Marcas/XML/airline/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE airline_DB SYSTEM "data_airline.dtd">
<airline_DB>
<airlines>
    <airline name="ryanair">
        <airplanes>
            <airplane reg_num="01" model="A380" capacity="125">
                <flight fl_num="V001" dep_airport="PMI" dest_airport="MAD" dep_date="23/06/2023 15:00" dest_date="23/06/2023 17:00"/>
            </airplane>
            <airplane reg_num="02" model="A380" capacity="125">
                <flight fl_num="V002" dep_airport="PMI" dest_airport="MEN" dep_date="23/06/2023 15:00" dest_date="23/06/2023 17:00"/>
            </airplane>
        </airplanes>
    </airline>
</airlines>
<passengers>
    <passenger name="Alejandro" surname="Vives" email="uno@gmail.com" seat="1">
        <booking idflight="V001" seat="C17"/>
    </passenger>
    <passenger name="Miguel" surname="Hernandez" email="noteimporta@gmail.com" seat="2">
        <booking idflight="V001" seat="C14"/>
    </passenger>
    <passenger name="Xisco" surname="Punk" email="e@gmail.com" seat="3">
        <booking idflight="V001" seat="C15"/>
    </passenger>
    <passenger name="Tomas" surname="Guerra" email="andfa@gmail.com" seat="4">
        <booking idflight="V001" seat="C16"/>
    </passenger>
</passengers>
<airports>
    <airport name="MAD"/>
    <airport name="PMI"/>
    <airport name="MEN"/>
    <airport name="IBZ"/>
</airports>
</airline_DB>
