=== A-vives/FP-/Lenguaje_de_Marcas/XML/ACT.5.1/4/data.dtd
<!ELEMENT ticket (fecha, precio_total, pago, comercio, compra)>
        <!ATTLIST ticket id ID #REQUIRED >
    <!ELEMENT fecha (#PCDATA)>
<!ELEMENT precio_total (precio_no_iva, IVA_tot, PVP_total)>
    <!ELEMENT precio_no_iva (#PCDATA)>
    <!ELEMENT IVA_tot (#PCDATA)>
    <!ELEMENT PVP_total (#PCDATA)>
        <!ATTLIST precio_total moneda NMTOKEN #REQUIRED>
<!ELEMENT pago (tarjeta | efectivo)>
    <!ELEMENT tarjeta (nombre)>
        <!ATTLIST tarjeta tipo CDATA #REQUIRED>
        <!ATTLIST tarjeta num  CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT efectivo (#PCDATA)>
        <!ELEMENT recibido (#PCDATA)>
        <!ELEMENT cambio (#PCDATA)>
<!ELEMENT comercio (nombre_comercio, direccion, CIF, telefono)>
    <!ELEMENT nombre_comercio (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT CIF (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
<!ELEMENT compra (nombre_compra, cantidad, precio_u_no_IVA, IVA, PVP)>
    <!ELEMENT nombre_compra (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT precio_u_no_IVA (#PCDATA)>
    <!ELEMENT IVA (#PCDATA)>
    <!ELEMENT PVP (#PCDATA)>

=== A-vives/FP-/Lenguaje_de_Marcas/XML/ACT.5.1/4/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ticket SYSTEM "data.dtd">
<ticket id="T001" >
    <fecha>22-07-2022</fecha>
    <precio_total moneda="EUR">
        <precio_no_iva>
         
        </precio_no_iva>
        <IVA_tot>
        </IVA_tot>
        <PVP_total>
        </PVP_total>
    </precio_total>
    <pago>
        <tarjeta tipo="" num="************1234">
            <nombre>
            Mariano
            </nombre>
        </tarjeta>
    </pago>
    <comercio>
        <nombre_comercio>

        </nombre_comercio>
        <direccion>

        </direccion>
        <CIF>

        </CIF>
        <telefono>

        </telefono>
    </comercio>

    <compra>
        <nombre_compra>

        </nombre_compra>
        <cantidad>

        </cantidad>
        <precio_u_no_IVA>

        </precio_u_no_IVA>
        <IVA>

        </IVA>
        <PVP>

        </PVP>
    </compra>

</ticket>
