=== A-vives/FP-/Lenguaje_de_Marcas/XML/ACT.5.1/6/data.dtd
<!ELEMENT seat (clientes, venta, coches, taller)>
<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente EMPTY>
    <!ATTLIST cliente id ID #REQUIRED>
    <!ATTLIST cliente nombre CDATA #REQUIRED>
    <!ATTLIST cliente apellido CDATA #REQUIRED>
    <!ATTLIST cliente direccion CDATA #REQUIRED>
    <!ATTLIST cliente tlf CDATA #REQUIRED>
<!ELEMENT venta EMPTY>
    <!ATTLIST venta id_cliente ID #REQUIRED>
    <!ATTLIST venta matricula CDATA #REQUIRED>
<!ELEMENT coches (coche+)>
<!ELEMENT coche EMPTY>
    <!ATTLIST coche tipo (nuevo | usado) #REQUIRED>
    <!ATTLIST coche id ID #IMPLIED>
    <!ATTLIST coche km CDATA #IMPLIED>
    <!ATTLIST coche modelo CDATA #IMPLIED>
    <!ATTLIST coche marca CDATA #IMPLIED>
    <!ATTLIST coche color CDATA #IMPLIED>
    <!ATTLIST coche matricula CDATA #IMPLIED>
    
<!ELEMENT taller (mecanicos, reparaciones)>
<!ELEMENT mecanicos (persona+)>
<!ELEMENT persona EMPTY>
    <!ATTLIST persona id ID #REQUIRED>
    <!ATTLIST persona nombre CDATA #REQUIRED>
    <!ATTLIST persona apellido CDATA #REQUIRED>
    <!ATTLIST persona contrato CDATA #REQUIRED>
    <!ATTLIST persona mobil CDATA #REQUIRED>
    <!ATTLIST persona salario CDATA #REQUIRED>
<!ELEMENT reparaciones (reparacion+)>
<!ELEMENT reparacion (mecanico+)>
<!ELEMENT mecanico EMPTY>
    <!ATTLIST mecanico idPersona IDREF #REQUIRED>

    <!ATTLIST reparacion matricula CDATA #REQUIRED>
    <!ATTLIST reparacion fecha CDATA #REQUIRED>
    <!ATTLIST reparacion horas CDATA #REQUIRED>


<!-- 
?- 0 - 1 
*- 0 - N
+- 1 - N
A, B - B despues de A
A|B - A รณ B, pero no A y B
-->

=== A-vives/FP-/Lenguaje_de_Marcas/XML/ACT.5.1/6/main.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE seat SYSTEM "data.dtd">
<seat>
    <clientes>
        <cliente id="C01" nombre="Alejandro" apellido="Vives" direccion="av.cojo,1" tlf="+34666776655"/>
        <cliente id="C02" nombre="Andres" apellido="Puertas" direccion="av.cojo,5" tlf="+34666776855"/>
        <cliente id="C03" nombre="Pedro" apellido="Navaja" direccion="av.cojo,9" tlf="+34666776658"/>
    </clientes>
    <venta id_cliente="C1" matricula="0013-HXS"/>
    <coches>
            <coche tipo="nuevo" id="N03" matricula="0010-HXS" modelo="Formentor" marca="SEAT" color="Blanco" />
            <coche tipo="nuevo" id="N02" matricula="0012-HXS" modelo="Leon" marca="SEAT" color="Blanco" />
            <coche tipo="usado" km="100000" matricula="0013-HXS" modelo="Ibiza" marca="SEAT" color="Blanco" />
            <coche tipo="usado" km="23000" matricula="0014-HXS" modelo="Cupra" marca="SEAT" color="Blanco" />
            <coche tipo="usado" km="50000" matricula="0015-HXS" modelo="Altea" marca="SEAT" color="Blanco" />
    </coches>
    <taller>
        <mecanicos>
            <persona id="M01" nombre="Marcos" apellido="Martin" contrato="26/04/2022" mobil="+34652256968" salario="1500" />
            <persona id="M02" nombre="Pedro" apellido="Hernandez" contrato="15/06/1998" mobil="+34635684215" salario="1500" />
            <persona id="M03" nombre="Sergi" apellido="Mendez" contrato="10/09/2000" mobil="+34632225252" salario="1500" />
            <persona id="M04" nombre="Hector" apellido="Martorell" contrato="04/03/09" mobil="+34711565859" salario="1500" />
        </mecanicos>
        <reparaciones>
          <reparacion matricula="0014-HXS" fecha="12/06/2017" horas="6">
          <mecanico idPersona="M01"/>
          </reparacion>
          <reparacion matricula="0015-HXS" fecha="22/08/2017" horas="5">
          <mecanico idPersona="M01"/>
          </reparacion>
          <reparacion matricula="0016-HXS" fecha="02/09/2017" horas="">
          <mecanico idPersona="M01"/>
          </reparacion>
        </reparaciones>
    </taller>
</seat>
