=== A-vives/FP-/Lenguaje_de_Marcas/XML/act_esquemas/act_2/squema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="Edad">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="130"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="fichas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="edad" type="Edad"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== A-vives/FP-/Lenguaje_de_Marcas/XML/act_esquemas/act_1/data.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<fichas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="squema.xsd">
    <persona>
        <nombre>Oliver Queen</nombre>
        <edad>55</edad>
    </persona>

    <persona>
        <nombre>Kevin Bacon</nombre>
        <edad>52</edad>
    </persona>

    <persona>
        <nombre>Rocket el mapache</nombre>
        <edad>5</edad>
    </persona>
</fichas>
